// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SOSBackClean.Data.Context;

#nullable disable

namespace SOSBackClean.Data.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20260527180551_fixFuncionarioIdNullable")]
    partial class fixFuncionarioIdNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SOSBackClean.Domain.Entities.Formulario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int?>("Funcionario_id")
                        .HasColumnType("int")
                        .HasColumnName("Funcionario_id");

                    b.Property<int>("Predio_id")
                        .HasColumnType("int")
                        .HasColumnName("Predio_id");

                    b.Property<int>("_andarOcorrencia")
                        .HasColumnType("int");

                    b.Property<string>("_arquivo")
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Arquivo");

                    b.Property<DateTime>("_dataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataCriacao");

                    b.Property<string>("_descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Descricao");

                    b.Property<string>("_feedBack")
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("FeedBack");

                    b.Property<int>("_infrator")
                        .HasColumnType("int")
                        .HasColumnName("Infrator");

                    b.Property<string>("_nomeOfendido")
                        .IsRequired()
                        .HasColumnType("nvarchar(70)")
                        .HasColumnName("Ofendido");

                    b.Property<string>("_protocolo")
                        .IsRequired()
                        .HasColumnType("varchar(40)")
                        .HasColumnName("Protocolo");

                    b.Property<string>("_sala")
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("Sala");

                    b.Property<bool>("_statusResolucao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("StatusResolucao");

                    b.Property<int>("_tipoInfracao")
                        .HasColumnType("int")
                        .HasColumnName("Infracao");

                    b.HasKey("Id");

                    b.HasIndex("Funcionario_id");

                    b.HasIndex("Predio_id");

                    b.HasIndex("_protocolo")
                        .IsUnique();

                    b.ToTable("Formulario", (string)null);
                });

            modelBuilder.Entity("SOSBackClean.Domain.Entities.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int>("_cargo")
                        .HasColumnType("int")
                        .HasColumnName("Cargo");

                    b.Property<string>("_foto")
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Foto");

                    b.Property<string>("_nome")
                        .IsRequired()
                        .HasColumnType("varchar(70)")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.ToTable("Funcionario", (string)null);
                });

            modelBuilder.Entity("SOSBackClean.Domain.Entities.Predio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("_nAndar")
                        .HasColumnType("int")
                        .HasColumnName("Numero_Andares");

                    b.Property<string>("_nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.ToTable("Predio", (string)null);
                });

            modelBuilder.Entity("SOSBackClean.Domain.Entities.Formulario", b =>
                {
                    b.HasOne("SOSBackClean.Domain.Entities.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("Funcionario_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SOSBackClean.Domain.Entities.Predio", "Predio")
                        .WithMany()
                        .HasForeignKey("Predio_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("Predio");
                });
#pragma warning restore 612, 618
        }
    }
}
